### ISSUE TITLE
enumerateDevices exception thrown

### ISSUE THREAD

**Issue by seungsunkim** [frostweep/PUN2VoiceWebGLUnity#9]
I built it with unity webgl and opened the index.html page, but I got the following error.

exception thrown: TypeError: Cannot read properties of undefined (reading 'enumerateDevices'), TypeError: Cannot read properties of undefined (reading 'enumerateDevices')
     at UnityMicrophone.refreshDevicesList (http://192.168.0.95/webglMicTest/Native/microphone.js:396:37)
     at UnityMicrophone.isPermissionGranted (http://192.168.0.95/webglMicTest/Native/microphone.js:148:14)
     at UnityMicrophone.requestPermission (http://192.168.0.95/webglMicTest/Native/microphone.js:125:18)
     at _requestPermission (http://192.168.0.95/webglMicTest/Build/build.web.framework.js:4296:29)

What's wrong?

**Comment by frostweep** [comment]
Hello,

you have to run app under https with valid ssl. its required.

**Comment by seungsunkim** [comment]
@frostweep Thank you.
It's resolved.

**Comment by seungsunkim** [comment]
@frostweep 
Thank you.
It's resolved.
